# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=100)),
                ('main_photo', models.ImageField(upload_to='img')),
                ('gallery_photo_1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_4', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_5', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_6', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_7', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_8', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_9', models.ImageField(blank=True, null=True, upload_to='img')),
                ('gallery_photo_10', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
