# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
