# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
