# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
