# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170710_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
