# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(choices=[('W', 'Works'), ('S', 'Skills')], max_length=50)),
            ],
        ),
    ]
